### ISSUE TITLE
Character animation is distorted

### ISSUE THREAD

**Issue by MidnightPhantom** [appgurueu/character_anim#6]
The character animation is distorted, The player walks with his legs in his body, hands above his head, etc. Here is a picture
![screenshot_20220428_155416](https://user-images.githubusercontent.com/96172170/166410748-26f9766f-2a9e-4dcf-9bdd-5ca845dc693c.png)

**Comment by appgurueu** [comment]
Is this the same bug as [reported on the forums](https://forum.minetest.net/viewtopic.php?p=407281#p407281) and [CDB](https://content.minetest.net/threads/2584/)? Do other players see you the way you're supposed to look? This would confirm my theory that the bug is related to changes in how 5.5 handles local animations.

**Comment by MidnightPhantom** [comment]
Yes. And for other players sorry but I haven't tested on multiplayer so I dunno

**Comment by appgurueu** [comment]
Closed by #3 in combination with misc. other fixes for local animation handling.
